# Transfer annotations to and from unfiltered object

In [1]:
from scatlastb_utils.io import read_anndata

In [2]:
cxg_file = 'data/pipeline/load_data/download/HLCAv1_core.h5ad'
unfiltered_file = 'data/input/HLCA_unfiltered.h5ad'

In [3]:
obs = read_anndata(cxg_file, obs='obs').obs
obs.index.name = 'index'
obs_unfiltered = read_anndata(unfiltered_file, obs='obs').obs
obs_unfiltered.index.name = 'index'

dask: False, backed: False
Read slot "obs", store as "obs"...
shape: (584944, 0)
dask: False, backed: False
Read slot "obs", store as "obs"...
shape: (587218, 0)

In [4]:
obs

,suspension_type,donor_id,is_primary_data,assay_ontology_term_id,cell_type_ontology_term_id,development_stage_ontology_term_id,disease_ontology_term_id,self_reported_ethnicity_ontology_term_id,tissue_ontology_term_id,sex_ontology_term_id,...,tissue_sampling_method,tissue_type,cell_type,assay,disease,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
index,,,,,,,,,,,,,,,,,,,,,
GCGACCATCCCTAACC_SC22,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009899,CL:0000583,HsapDv:0000143,PATO:0000461,HANCESTRO:0005,UBERON:0008946,PATO:0000383,...,donor_lung,tissue,alveolar macrophage,10x 3' v2,normal,female,lung parenchyma,European,49-year-old stage,y3(xbM64-M
P2_1_GCGCAACCAGTTAACC,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009899,CL:0000623,HsapDv:0000140,PATO:0000461,HANCESTRO:0005,UBERON:0008946,PATO:0000384,...,surgical_resection,tissue,natural killer cell,10x 3' v2,normal,male,lung parenchyma,European,46-year-old stage,A>+$XL~PxD
GCTCTGTAGTGCTGCC_SC27,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009899,CL:0002063,HsapDv:0000141,PATO:0000461,HANCESTRO:0005,UBERON:0008946,PATO:0000383,...,donor_lung,tissue,pulmonary alveolar type 2 cell,10x 3' v2,normal,female,lung parenchyma,European,47-year-old stage,5jcAkve8k5
P2_8_TTAGGACGTTCAGGCC,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009899,CL:0000583,HsapDv:0000140,PATO:0000461,HANCESTRO:0005,UBERON:0001005,PATO:0000384,...,surgical_resection,tissue,alveolar macrophage,10x 3' v2,normal,male,respiratory airway,European,46-year-old stage,k*BkT>5OqJ
CTTGATTGTCAGTTTG_T164,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009922,CL:0002633,HsapDv:0000160,PATO:0000461,HANCESTRO:0005,UBERON:0001005,PATO:0000384,...,donor_lung,tissue,respiratory basal cell,10x 3' v3,normal,male,respiratory airway,European,66-year-old stage,zJo=(;6B>Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACCTTTACATTAACCG_T120,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009899,CL:0002633,HsapDv:0000151,PATO:0000461,HANCESTRO:0005,UBERON:0001005,PATO:0000383,...,donor_lung,tissue,respiratory basal cell,10x 3' v2,normal,female,respiratory airway,European,57-year-old stage,1u$14E;a$U
CATTATCTCCATGAAC_F01639,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0011025,CL:0002399,HsapDv:0000147,PATO:0000461,HANCESTRO:0005,UBERON:0008946,PATO:0000384,...,donor_lung,tissue,CD1c-positive myeloid dendritic cell,10x 5' v1,normal,male,lung parenchyma,European,53-year-old stage,$3Xp*6c51x
AGGCCGTGTGTGACCC-SC56,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009899,CL:0002063,HsapDv:0000151,PATO:0000461,HANCESTRO:0005,UBERON:0008946,PATO:0000383,...,donor_lung,tissue,pulmonary alveolar type 2 cell,10x 3' v2,normal,female,lung parenchyma,European,57-year-old stage,7#E>)wqFoi
CGATGGCAGCAGGCTA-1-2,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0011025,CL:0000158,HsapDv:0000135,PATO:0000461,HANCESTRO:0005,UBERON:0000004,PATO:0000384,...,scraping,tissue,club cell,10x 5' v1,normal,male,nose,European,41-year-old stage,xylivC=ha2
AATCGGTGTCGGCACT-1-4,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009900,CL:0000158,HsapDv:0000121,PATO:0000461,HANCESTRO:0005 || HANCESTRO:0008,UBERON:0000004,PATO:0000383,...,scraping,tissue,club cell,10x 5' v2,normal,female,nose,European || Asian,27-year-old stage,|8>G}9ymyx

In [5]:
obs_unfiltered

,sample,original_celltype_ann,study_long,study,last_author_PI,subject_ID,subject_ID_as_published,pre_or_postnatal,age_in_years,age_range,...,anatomical_region_ccf_score,manual_ann,leiden_4,reannotation_type,leiden_5,entropy_subject_ID_leiden_3,entropy_dataset_leiden_3,entropy_original_ann_level_1_leiden_3,entropy_original_ann_level_2_clean_leiden_3,entropy_original_ann_level_3_clean_leiden_3
index,,,,,,,,,,,,,,,,,,,,,
7119453_TACTCATGTAGGCATG,7119453,Endothelial,Sanger_Teichman_Meyer_2019VieiraBraga,Teichmann_Meyer_2019,Teichmann_Meyer,284C,nan,postnatal,NaN,55-60,...,0.97,Arterial EC,2.4.2.0,"underannotated, correct",nan,0.000000,0.000000,0.000000,0.000000,NaN
GCGACCATCCCTAACC_SC22,SC22,Alveolar macrophages,Northwestern_Misharin_Budinger_2018Reyfman,Misharin_Budinger_2018,Misharin_Budinger,Donor_05,Donor_05,postnatal,49.0,nan,...,0.97,Macrophages,1.0.0.0,correctly_annotated,nan,2.602398,1.664049,0.177918,0.182714,0.277385
P2_1_GCGCAACCAGTTAACC,distal 2,Natural Killer,Stanford_Krasnow_2020Travaglini,Krasnow_2020,Krasnow,donor 2,nan,postnatal,46.0,nan,...,0.97,Innate Lymphoid Cell NK,1.3.0.0,correctly_annotated,nan,2.729274,1.461924,0.013459,0.015608,0.326962
GCTCTGTAGTGCTGCC_SC27,SC27,Alveolar epithelial type 2 cells,Northwestern_Misharin_Budinger_2018Reyfman,Misharin_Budinger_2018,Misharin_Budinger,Donor_07,Donor_07,postnatal,47.0,nan,...,0.97,AT2,0.1.2.0,correctly_annotated,nan,2.006138,1.381972,0.280016,0.208872,0.388602
P2_8_TTAGGACGTTCAGGCC,medial 2,Macrophage,Stanford_Krasnow_2020Travaglini,Krasnow_2020,Krasnow,donor 2,nan,postnatal,46.0,nan,...,0.81,Macrophages,1.0.2.0,correctly_annotated,nan,1.192024,1.005008,0.002307,0.019563,0.062629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACCTTTACATTAACCG_T120,T120,KRT8.high,NJH_Seibold_2020Goldfarbmuren,Seibold_2020,Seibold,T120,T120,postnatal,57.0,nan,...,0.36,Basal,0.0.2.3,correctly_annotated,nan,2.790810,1.631233,0.016913,0.273477,0.387291
CATTATCTCCATGAAC_F01639,F01639,cDC1,TGen_VUMC_Banovich_Kropski_2020Habermann_and_u...,Banovich_Kropski_2020,Banovich_Kropski,THD0008,THD0008,postnatal,53.0,nan,...,0.97,Dendritic cells,1.2.1.0,correctly_annotated,nan,3.716129,2.148653,0.099850,0.091353,1.151454
AGGCCGTGTGTGACCC-SC56,SC56,6 AT2,Pittsburgh_Lafyatis_Rojas_2019Morse,Lafyatis_Rojas_2019,Lafyatis_Rojas,lafy_donor_4,nan,postnatal,57.0,nan,...,0.97,AT2,0.1.2.0,correctly_annotated,nan,2.006138,1.381972,0.280016,0.208872,0.388602
CGATGGCAGCAGGCTA-1-2,SC174_SC173,Club,Northwestern_Jain_Misharin_2021_unpubl,Jain_Misharin_2021,Jain_Misharin,2020-3173-NC008,nan,postnatal,41.0,nan,...,0.00,Secretory,0.2.1.0,correctly_annotated,nan,2.782702,1.404169,0.004833,0.014457,0.700806
AATCGGTGTCGGCACT-1-4,SC182,Club,Northwestern_Jain_Misharin_2021_unpubl,Jain_Misharin_2021,Jain_Misharin,2020-3173-NC004,nan,postnatal,27.0,nan,...,0.00,Secretory,0.2.1.0,correctly_annotated,nan,2.782702,1.404169,0.004833,0.014457,0.700806

## Check overlapping barcodes

In [6]:
obs.index.difference(obs_unfiltered.index)

Index([], dtype='object', name='index')

In [7]:
obs.index.intersection(obs_unfiltered.index)

Index(['GCGACCATCCCTAACC_SC22', 'P2_1_GCGCAACCAGTTAACC',
       'GCTCTGTAGTGCTGCC_SC27', 'P2_8_TTAGGACGTTCAGGCC',
       'CTTGATTGTCAGTTTG_T164', 'P3_3_CCACTACTCATTGCGA',
       'P2_1_CAGCAGCGTGTTGAGG', 'P1_4_TTGCGTCAGCTTCGCG',
       'GTCACGGAGACGCAAC_F02617', 'CAGCCACAGTCACTA_GRO-03_biopsy',
       ...
       'CGGACACAGCCATCGC-1-HCATisStab7659970', 'P2_3_GCGCCAATCGGTCTAA',
       'CAGAATCCATGGTAGG-1-4', 'TTCTACACATACTACG_T85',
       'ATGAGGGTCCCTCTCC_SC143', 'ACCTTTACATTAACCG_T120',
       'CATTATCTCCATGAAC_F01639', 'AGGCCGTGTGTGACCC-SC56',
       'CGATGGCAGCAGGCTA-1-2', 'AATCGGTGTCGGCACT-1-4'],
      dtype='object', name='index', length=584944)

## Columns missing from CxG

In [8]:
cols_not_in_cxg = [
    col for col in obs_unfiltered.columns
    if col not in obs.columns
]

In [9]:
cols_not_in_cxg

['original_celltype_ann',
 'study_long',
 'last_author_PI',
 'subject_ID',
 'subject_ID_as_published',
 'pre_or_postnatal',
 'age_in_years',
 'ethnicity',
 'mixed_ethnicity',
 'smoking_history',
 'known_lung_disease',
 'condition',
 'sample_type',
 'anatomical_region_coarse',
 'anatomical_region_detailed',
 'cells_or_nuclei',
 'single_cell_platform',
 "3'_or_5'",
 'enrichment',
 'reference_genome_coarse',
 'ensembl_release_reference_genome',
 'cell_ranger_version',
 'disease_status',
 'cultured',
 'cell_viability_%',
 'comments',
 'Processing_site',
 'anatomical_region_level_1',
 'anatomical_region_level_2',
 'anatomical_region_level_3',
 'anatomical_region_highest_res',
 'age',
 'original_ann_new',
 'n_genes',
 'total_counts',
 'mito_frac',
 'ribo_frac',
 'compl',
 'original_ann_level_1_clean',
 'original_ann_level_2_clean',
 'original_ann_level_3_clean',
 'original_ann_level_4_clean',
 'original_ann_level_5_clean',
 'manual_ann']

In [17]:
obs_unfiltered[cols_not_in_cxg]

,original_celltype_ann,study_long,last_author_PI,subject_ID,subject_ID_as_published,pre_or_postnatal,age_in_years,ethnicity,mixed_ethnicity,smoking_history,...,total_counts,mito_frac,ribo_frac,compl,original_ann_level_1_clean,original_ann_level_2_clean,original_ann_level_3_clean,original_ann_level_4_clean,original_ann_level_5_clean,manual_ann
index,,,,,,,,,,,,,,,,,,,,,
7119453_TACTCATGTAGGCATG,Endothelial,Sanger_Teichman_Meyer_2019VieiraBraga,Teichmann_Meyer,284C,nan,postnatal,NaN,white,nan,"25 years, 20 per day",...,5326.0,0.025347,0.130680,0.321817,Endothelial,Blood vessels,None,None,None,Arterial EC
GCGACCATCCCTAACC_SC22,Alveolar macrophages,Northwestern_Misharin_Budinger_2018Reyfman,Misharin_Budinger,Donor_05,Donor_05,postnatal,49.0,white,nan,nan,...,10380.0,0.026493,0.174952,0.234875,Immune,Myeloid,Macrophages,Alveolar macrophages,None,Macrophages
P2_1_GCGCAACCAGTTAACC,Natural Killer,Stanford_Krasnow_2020Travaglini,Krasnow,donor 2,nan,postnatal,46.0,white,nan,nan,...,1599.0,0.016886,0.174484,0.437774,Immune,Lymphoid,Innate Lymphoid Cell NK,NK cells,None,Innate Lymphoid Cell NK
GCTCTGTAGTGCTGCC_SC27,Alveolar epithelial type 2 cells,Northwestern_Misharin_Budinger_2018Reyfman,Misharin_Budinger,Donor_07,Donor_07,postnatal,47.0,white,nan,nan,...,3115.0,0.022793,0.280257,0.385233,Epithelial,Alveolar epithelium,AT2,None,None,AT2
P2_8_TTAGGACGTTCAGGCC,Macrophage,Stanford_Krasnow_2020Travaglini,Krasnow,donor 2,nan,postnatal,46.0,white,nan,nan,...,17482.0,0.054628,0.129676,0.187965,Immune,Myeloid,Macrophages,Alveolar macrophages,None,Macrophages
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACCTTTACATTAACCG_T120,KRT8.high,NJH_Seibold_2020Goldfarbmuren,Seibold,T120,T120,postnatal,57.0,white,nan,90.0,...,15281.0,0.054643,0.293633,0.207905,Epithelial,Airway epithelium,Basal,KRT8 high basal,None,Basal
CATTATCTCCATGAAC_F01639,cDC1,TGen_VUMC_Banovich_Kropski_2020Habermann_and_u...,Banovich_Kropski,THD0008,THD0008,postnatal,53.0,white,nan,nan,...,10179.0,0.042146,0.175558,0.254445,Immune,Myeloid,Dendritic cells,DC1,None,Dendritic cells
AGGCCGTGTGTGACCC-SC56,6 AT2,Pittsburgh_Lafyatis_Rojas_2019Morse,Lafyatis_Rojas,lafy_donor_4,nan,postnatal,57.0,white,nan,nan,...,11924.0,0.055686,0.246226,0.238846,Epithelial,Alveolar epithelium,AT2,None,None,AT2
CGATGGCAGCAGGCTA-1-2,Club,Northwestern_Jain_Misharin_2021_unpubl,Jain_Misharin,2020-3173-NC008,nan,postnatal,41.0,white,nan,nan,...,4501.0,0.065763,0.098867,0.421906,Epithelial,Airway epithelium,Secretory,Club,None,Secretory
AATCGGTGTCGGCACT-1-4,Club,Northwestern_Jain_Misharin_2021_unpubl,Jain_Misharin,2020-3173-NC004,nan,postnatal,27.0,mixed,white/asian,nan,...,1503.0,0.089820,0.156354,0.552229,Epithelial,Airway epithelium,Secretory,Club,None,Secretory

In [10]:
obs_unfiltered[cols_not_in_cxg].to_csv('data/input/HLCA_unfiltered_anno.tsv', sep='\t')

In [11]:
for col in cols_not_in_cxg:
    obs[col] = obs_unfiltered[col]

In [12]:
obs[cols_not_in_cxg]

,original_celltype_ann,study_long,last_author_PI,subject_ID,subject_ID_as_published,pre_or_postnatal,age_in_years,ethnicity,mixed_ethnicity,smoking_history,...,total_counts,mito_frac,ribo_frac,compl,original_ann_level_1_clean,original_ann_level_2_clean,original_ann_level_3_clean,original_ann_level_4_clean,original_ann_level_5_clean,manual_ann
index,,,,,,,,,,,,,,,,,,,,,
GCGACCATCCCTAACC_SC22,Alveolar macrophages,Northwestern_Misharin_Budinger_2018Reyfman,Misharin_Budinger,Donor_05,Donor_05,postnatal,49.0,white,nan,nan,...,10380.0,0.026493,0.174952,0.234875,Immune,Myeloid,Macrophages,Alveolar macrophages,None,Macrophages
P2_1_GCGCAACCAGTTAACC,Natural Killer,Stanford_Krasnow_2020Travaglini,Krasnow,donor 2,nan,postnatal,46.0,white,nan,nan,...,1599.0,0.016886,0.174484,0.437774,Immune,Lymphoid,Innate Lymphoid Cell NK,NK cells,None,Innate Lymphoid Cell NK
GCTCTGTAGTGCTGCC_SC27,Alveolar epithelial type 2 cells,Northwestern_Misharin_Budinger_2018Reyfman,Misharin_Budinger,Donor_07,Donor_07,postnatal,47.0,white,nan,nan,...,3115.0,0.022793,0.280257,0.385233,Epithelial,Alveolar epithelium,AT2,None,None,AT2
P2_8_TTAGGACGTTCAGGCC,Macrophage,Stanford_Krasnow_2020Travaglini,Krasnow,donor 2,nan,postnatal,46.0,white,nan,nan,...,17482.0,0.054628,0.129676,0.187965,Immune,Myeloid,Macrophages,Alveolar macrophages,None,Macrophages
CTTGATTGTCAGTTTG_T164,KRT8.high,NJH_Seibold_2020Goldfarbmuren,Seibold,T164,T164,postnatal,66.0,white,nan,0.0,...,54144.0,0.121195,0.174885,0.127272,Epithelial,Airway epithelium,Basal,KRT8 high basal,None,Basal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACCTTTACATTAACCG_T120,KRT8.high,NJH_Seibold_2020Goldfarbmuren,Seibold,T120,T120,postnatal,57.0,white,nan,90.0,...,15281.0,0.054643,0.293633,0.207905,Epithelial,Airway epithelium,Basal,KRT8 high basal,None,Basal
CATTATCTCCATGAAC_F01639,cDC1,TGen_VUMC_Banovich_Kropski_2020Habermann_and_u...,Banovich_Kropski,THD0008,THD0008,postnatal,53.0,white,nan,nan,...,10179.0,0.042146,0.175558,0.254445,Immune,Myeloid,Dendritic cells,DC1,None,Dendritic cells
AGGCCGTGTGTGACCC-SC56,6 AT2,Pittsburgh_Lafyatis_Rojas_2019Morse,Lafyatis_Rojas,lafy_donor_4,nan,postnatal,57.0,white,nan,nan,...,11924.0,0.055686,0.246226,0.238846,Epithelial,Alveolar epithelium,AT2,None,None,AT2
CGATGGCAGCAGGCTA-1-2,Club,Northwestern_Jain_Misharin_2021_unpubl,Jain_Misharin,2020-3173-NC008,nan,postnatal,41.0,white,nan,nan,...,4501.0,0.065763,0.098867,0.421906,Epithelial,Airway epithelium,Secretory,Club,None,Secretory
AATCGGTGTCGGCACT-1-4,Club,Northwestern_Jain_Misharin_2021_unpubl,Jain_Misharin,2020-3173-NC004,nan,postnatal,27.0,mixed,white/asian,nan,...,1503.0,0.089820,0.156354,0.552229,Epithelial,Airway epithelium,Secretory,Club,None,Secretory

## Columns missing from unfiltered

In [13]:
cols_not_in_unf = [
    col for col in obs.columns
    if col not in obs_unfiltered.columns
]

cols_not_in_unf

['suspension_type',
 'donor_id',
 'is_primary_data',
 'assay_ontology_term_id',
 'cell_type_ontology_term_id',
 'development_stage_ontology_term_id',
 'disease_ontology_term_id',
 'self_reported_ethnicity_ontology_term_id',
 'tissue_ontology_term_id',
 'sex_ontology_term_id',
 'age_or_mean_of_age_range',
 'ann_coarse_for_GWAS_and_modeling',
 'ann_finest_level',
 'ann_level_1',
 'ann_level_2',
 'ann_level_3',
 'ann_level_4',
 'ann_level_5',
 'lung_condition',
 'mixed_ancestry',
 'original_ann_nonharmonized',
 'reference_genome',
 'tissue_level_2',
 'tissue_level_3',
 'tissue_sampling_method',
 'tissue_type',
 'cell_type',
 'assay',
 'disease',
 'tissue',
 'self_reported_ethnicity',
 'development_stage',
 'observation_joinid']

In [14]:
for col in cols_not_in_unf:
    obs_unfiltered[col] = obs[col]

In [15]:
obs_unfiltered.shape[0] - obs.shape[0]

2274

In [16]:
obs_unfiltered[cols_not_in_unf]

,suspension_type,donor_id,is_primary_data,assay_ontology_term_id,cell_type_ontology_term_id,development_stage_ontology_term_id,disease_ontology_term_id,self_reported_ethnicity_ontology_term_id,tissue_ontology_term_id,sex_ontology_term_id,...,tissue_level_3,tissue_sampling_method,tissue_type,cell_type,assay,disease,tissue,self_reported_ethnicity,development_stage,observation_joinid
index,,,,,,,,,,,,,,,,,,,,,
7119453_TACTCATGTAGGCATG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GCGACCATCCCTAACC_SC22,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009899,CL:0000583,HsapDv:0000143,PATO:0000461,HANCESTRO:0005,UBERON:0008946,PATO:0000383,...,NaN,donor_lung,tissue,alveolar macrophage,10x 3' v2,normal,lung parenchyma,European,49-year-old stage,y3(xbM64-M
P2_1_GCGCAACCAGTTAACC,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009899,CL:0000623,HsapDv:0000140,PATO:0000461,HANCESTRO:0005,UBERON:0008946,PATO:0000384,...,NaN,surgical_resection,tissue,natural killer cell,10x 3' v2,normal,lung parenchyma,European,46-year-old stage,A>+$XL~PxD
GCTCTGTAGTGCTGCC_SC27,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009899,CL:0002063,HsapDv:0000141,PATO:0000461,HANCESTRO:0005,UBERON:0008946,PATO:0000383,...,NaN,donor_lung,tissue,pulmonary alveolar type 2 cell,10x 3' v2,normal,lung parenchyma,European,47-year-old stage,5jcAkve8k5
P2_8_TTAGGACGTTCAGGCC,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009899,CL:0000583,HsapDv:0000140,PATO:0000461,HANCESTRO:0005,UBERON:0001005,PATO:0000384,...,distal airways middle right lobe,surgical_resection,tissue,alveolar macrophage,10x 3' v2,normal,respiratory airway,European,46-year-old stage,k*BkT>5OqJ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACCTTTACATTAACCG_T120,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009899,CL:0002633,HsapDv:0000151,PATO:0000461,HANCESTRO:0005,UBERON:0001005,PATO:0000383,...,NaN,donor_lung,tissue,respiratory basal cell,10x 3' v2,normal,respiratory airway,European,57-year-old stage,1u$14E;a$U
CATTATCTCCATGAAC_F01639,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0011025,CL:0002399,HsapDv:0000147,PATO:0000461,HANCESTRO:0005,UBERON:0008946,PATO:0000384,...,NaN,donor_lung,tissue,CD1c-positive myeloid dendritic cell,10x 5' v1,normal,lung parenchyma,European,53-year-old stage,$3Xp*6c51x
AGGCCGTGTGTGACCC-SC56,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009899,CL:0002063,HsapDv:0000151,PATO:0000461,HANCESTRO:0005,UBERON:0008946,PATO:0000383,...,NaN,donor_lung,tissue,pulmonary alveolar type 2 cell,10x 3' v2,normal,lung parenchyma,European,57-year-old stage,7#E>)wqFoi
CGATGGCAGCAGGCTA-1-2,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0011025,CL:0000158,HsapDv:0000135,PATO:0000461,HANCESTRO:0005,UBERON:0000004,PATO:0000384,...,inferior turbinate right nostril,scraping,tissue,club cell,10x 5' v1,normal,nose,European,41-year-old stage,xylivC=ha2
AATCGGTGTCGGCACT-1-4,cell,homosapiens_None_2023_None_sikkemalisa_001_d10...,False,EFO:0009900,CL:0000158,HsapDv:0000121,PATO:0000461,HANCESTRO:0005 || HANCESTRO:0008,UBERON:0000004,PATO:0000383,...,inferior turbinate right nostril,scraping,tissue,club cell,10x 5' v2,normal,nose,European || Asian,27-year-old stage,|8>G}9ymyx

## Explore "sequencing_platform"

In [18]:
obs[['assay', 'single_cell_platform']].drop_duplicates().value_counts('assay')

assay
10x 3' v2    1
10x 5' v2    1
10x 3' v1    1
10x 3' v3    1
10x 5' v1    1
Name: count, dtype: int64

In [19]:
obs[['assay', 'single_cell_platform']].drop_duplicates().value_counts('single_cell_platform')

single_cell_platform
10x_3'_v1    1
10x_3'_v2    1
10x_3'_v3    1
10x_5'_v1    1
10x_5'_v2    1
Name: count, dtype: int64

In [21]:
obs[['assay', 'sequencing_platform']].drop_duplicates().value_counts('sequencing_platform')

sequencing_platform
Illumina NovaSeq 6000                         4
Illumina HiSeq 4000                           2
Illumina NextSeq 500                          2
Illumina NovaSeq 6000 S4                      2
Illumina NovaSeq 6000 S1                      1
Illumina NovaSeq 6000 S2                      1
Illumina NovaSeq 6000 SP                      1
Illumina NovaSeq 6000; Illumina HiSeq 4000    1
Name: count, dtype: int64

In [42]:
obs.value_counts(['study', 'sequencing_platform'], sort=False)

study                   sequencing_platform
Banovich_Kropski_2020   Illumina NovaSeq 6000 S1                      41001
                        Illumina NovaSeq 6000 S2                      21371
                        Illumina NovaSeq 6000 S4                      57225
                        Illumina NovaSeq 6000 SP                       1920
Barbry_Leroy_2020       Illumina NextSeq 500                          74487
Jain_Misharin_2021      Illumina NovaSeq 6000                         45557
Krasnow_2020            Illumina NovaSeq 6000                         60982
Lafyatis_Rojas_2019     Illumina NextSeq 500                          24181
Meyer_2019              Illumina HiSeq 4000                           35554
Misharin_2021           Illumina HiSeq 4000                           28029
                        Illumina NovaSeq 6000                         36814
Misharin_Budinger_2018  Illumina HiSeq 4000                           41220
Nawijn_2021             Illumina HiSeq 4000                           42361
                        Illumina NovaSeq 6000                         28041
Seibold_2020            Illumina NovaSeq 6000                         27778
                        Illumina NovaSeq 6000; Illumina HiSeq 4000     5815
Teichmann_Meyer_2019    Illumina HiSeq 4000                           12231
Name: count, dtype: int64

In [22]:
obs[['assay', 'sequencing_platform']].drop_duplicates().value_counts('assay')

assay
10x 5' v1    6
10x 3' v2    4
10x 5' v2    2
10x 3' v3    2
10x 3' v1    1
Name: count, dtype: int64

In [23]:
obs[['assay', 'study', 'sequencing_platform']].drop_duplicates().value_counts('study')

study
Banovich_Kropski_2020     6
Seibold_2020              3
Jain_Misharin_2021        2
Nawijn_2021               2
Lafyatis_Rojas_2019       2
Misharin_2021             2
Barbry_Leroy_2020         1
Meyer_2019                1
Krasnow_2020              1
Misharin_Budinger_2018    1
Teichmann_Meyer_2019      1
Name: count, dtype: int64

In [28]:
obs.query('study == "Banovich_Kropski_2020"').value_counts(
    ['Processing_site', 'assay', 'sequencing_platform'],
    sort=False
)

Processing_site  assay      sequencing_platform
TGen             10x 5' v2  Illumina NovaSeq 6000 S4     3946
                 10x 5' v1  Illumina NovaSeq 6000 S1     8354
                            Illumina NovaSeq 6000 S2    10897
                            Illumina NovaSeq 6000 S4     1465
                            Illumina NovaSeq 6000 SP     1920
VUMC             10x 5' v1  Illumina NovaSeq 6000 S1    32647
                            Illumina NovaSeq 6000 S2    10474
                            Illumina NovaSeq 6000 S4    51814
Name: count, dtype: int64

In [37]:
obs.columns.to_list()

['suspension_type',
 'donor_id',
 'is_primary_data',
 'assay_ontology_term_id',
 'cell_type_ontology_term_id',
 'development_stage_ontology_term_id',
 'disease_ontology_term_id',
 'self_reported_ethnicity_ontology_term_id',
 'tissue_ontology_term_id',
 'sex_ontology_term_id',
 'BMI',
 'age_or_mean_of_age_range',
 'age_range',
 'anatomical_region_ccf_score',
 'ann_coarse_for_GWAS_and_modeling',
 'ann_finest_level',
 'ann_level_1',
 'ann_level_2',
 'ann_level_3',
 'ann_level_4',
 'ann_level_5',
 'cause_of_death',
 'dataset',
 'entropy_dataset_leiden_3',
 'entropy_original_ann_level_1_leiden_3',
 'entropy_original_ann_level_2_clean_leiden_3',
 'entropy_original_ann_level_3_clean_leiden_3',
 'entropy_subject_ID_leiden_3',
 'fresh_or_frozen',
 'leiden_1',
 'leiden_2',
 'leiden_3',
 'leiden_4',
 'leiden_5',
 'log10_total_counts',
 'lung_condition',
 'mixed_ancestry',
 'n_genes_detected',
 'original_ann_highest_res',
 'original_ann_level_1',
 'original_ann_level_2',
 'original_ann_level_3',
 'original_ann_level_4',
 'original_ann_level_5',
 'original_ann_nonharmonized',
 'reannotation_type',
 'reference_genome',
 'sample',
 'scanvi_label',
 'sequencing_platform',
 'size_factors',
 'smoking_status',
 'study',
 'subject_type',
 'tissue_dissociation_protocol',
 'tissue_level_2',
 'tissue_level_3',
 'tissue_sampling_method',
 'tissue_type',
 'cell_type',
 'assay',
 'disease',
 'sex',
 'tissue',
 'self_reported_ethnicity',
 'development_stage',
 'observation_joinid',
 'original_celltype_ann',
 'study_long',
 'last_author_PI',
 'subject_ID',
 'subject_ID_as_published',
 'pre_or_postnatal',
 'age_in_years',
 'ethnicity',
 'mixed_ethnicity',
 'smoking_history',
 'known_lung_disease',
 'condition',
 'sample_type',
 'anatomical_region_coarse',
 'anatomical_region_detailed',
 'cells_or_nuclei',
 'single_cell_platform',
 "3'_or_5'",
 'enrichment',
 'reference_genome_coarse',
 'ensembl_release_reference_genome',
 'cell_ranger_version',
 'disease_status',
 'cultured',
 'cell_viability_%',
 'comments',
 'Processing_site',
 'anatomical_region_level_1',
 'anatomical_region_level_2',
 'anatomical_region_level_3',
 'anatomical_region_highest_res',
 'age',
 'original_ann_new',
 'n_genes',
 'total_counts',
 'mito_frac',
 'ribo_frac',
 'compl',
 'original_ann_level_1_clean',
 'original_ann_level_2_clean',
 'original_ann_level_3_clean',
 'original_ann_level_4_clean',
 'original_ann_level_5_clean',
 'manual_ann']

In [46]:
obs.query('study == "Banovich_Kropski_2020"').value_counts(
    ['Processing_site', 'assay', 'sequencing_platform'],
    sort=False
)

Processing_site  assay      sequencing_platform
TGen             10x 5' v2  Illumina NovaSeq 6000 S4     3946
                 10x 5' v1  Illumina NovaSeq 6000 S1     8354
                            Illumina NovaSeq 6000 S2    10897
                            Illumina NovaSeq 6000 S4     1465
                            Illumina NovaSeq 6000 SP     1920
VUMC             10x 5' v1  Illumina NovaSeq 6000 S1    32647
                            Illumina NovaSeq 6000 S2    10474
                            Illumina NovaSeq 6000 S4    51814
Name: count, dtype: int64

In [47]:
obs.query('study == "Banovich_Kropski_2020"').value_counts(
    ['Processing_site', 'assay', 'sequencing_platform', 'sample'],
    sort=False
)

Processing_site  assay      sequencing_platform       sample
TGen             10x 5' v2  Illumina NovaSeq 6000 S4  F02730      1411
                                                      F02992      1753
                                                      F03045       782
                 10x 5' v1  Illumina NovaSeq 6000 S1  F01157      2542
                                                      F01365      1636
                                                      F01366      1573
                                                      F01367      1307
                                                      F01403      1296
                            Illumina NovaSeq 6000 S2  F01607      4201
                                                      F01639      3252
                                                      F01641      1739
                                                      F01692       748
                                                      F01874       957
                            Illumina NovaSeq 6000 S4  F02509      1465
                            Illumina NovaSeq 6000 SP  F02092      1920
VUMC             10x 5' v1  Illumina NovaSeq 6000 S1  F00409      1208
                                                      F01394      5972
                                                      F01483       601
                                                      F01494       142
                                                      F01495       136
                                                      F01506        47
                                                      F01511       436
                                                      F01513       400
                                                      VUHD66      3440
                                                      VUHD67     10093
                                                      VUHD68      7850
                                                      VUHD70      2322
                            Illumina NovaSeq 6000 S2  F01851      9134
                                                      F01853      1332
                                                      F01869         8
                            Illumina NovaSeq 6000 S4  F02522      7560
                                                      F02524      7286
                                                      F02526      3474
                                                      F02528      4305
                                                      F02607      6180
                                                      F02609       140
                                                      F02611      9331
                                                      F02613      1028
                                                      F02617      9395
                                                      VUHD101     3115
Name: count, dtype: int64

In [45]:
obs.query('study == "Banovich_Kropski_2020"').value_counts(
    ['Processing_site', 'assay', 'sample', 'sequencing_platform'],
    sort=False
)

Processing_site  assay      sample   sequencing_platform
TGen             10x 5' v2  F02730   Illumina NovaSeq 6000 S4     1411
                            F02992   Illumina NovaSeq 6000 S4     1753
                            F03045   Illumina NovaSeq 6000 S4      782
                 10x 5' v1  F01157   Illumina NovaSeq 6000 S1     2542
                            F01365   Illumina NovaSeq 6000 S1     1636
                            F01366   Illumina NovaSeq 6000 S1     1573
                            F01367   Illumina NovaSeq 6000 S1     1307
                            F01403   Illumina NovaSeq 6000 S1     1296
                            F01607   Illumina NovaSeq 6000 S2     4201
                            F01639   Illumina NovaSeq 6000 S2     3252
                            F01641   Illumina NovaSeq 6000 S2     1739
                            F01692   Illumina NovaSeq 6000 S2      748
                            F01874   Illumina NovaSeq 6000 S2      957
                            F02092   Illumina NovaSeq 6000 SP     1920
                            F02509   Illumina NovaSeq 6000 S4     1465
VUMC             10x 5' v1  F00409   Illumina NovaSeq 6000 S1     1208
                            F01394   Illumina NovaSeq 6000 S1     5972
                            F01483   Illumina NovaSeq 6000 S1      601
                            F01494   Illumina NovaSeq 6000 S1      142
                            F01495   Illumina NovaSeq 6000 S1      136
                            F01506   Illumina NovaSeq 6000 S1       47
                            F01511   Illumina NovaSeq 6000 S1      436
                            F01513   Illumina NovaSeq 6000 S1      400
                            F01851   Illumina NovaSeq 6000 S2     9134
                            F01853   Illumina NovaSeq 6000 S2     1332
                            F01869   Illumina NovaSeq 6000 S2        8
                            F02522   Illumina NovaSeq 6000 S4     7560
                            F02524   Illumina NovaSeq 6000 S4     7286
                            F02526   Illumina NovaSeq 6000 S4     3474
                            F02528   Illumina NovaSeq 6000 S4     4305
                            F02607   Illumina NovaSeq 6000 S4     6180
                            F02609   Illumina NovaSeq 6000 S4      140
                            F02611   Illumina NovaSeq 6000 S4     9331
                            F02613   Illumina NovaSeq 6000 S4     1028
                            F02617   Illumina NovaSeq 6000 S4     9395
                            VUHD101  Illumina NovaSeq 6000 S4     3115
                            VUHD66   Illumina NovaSeq 6000 S1     3440
                            VUHD67   Illumina NovaSeq 6000 S1    10093
                            VUHD68   Illumina NovaSeq 6000 S1     7850
                            VUHD70   Illumina NovaSeq 6000 S1     2322
Name: count, dtype: int64

In [32]:
obs.value_counts(['study', 'Processing_site'], dropna=False, sort=False)

study                   Processing_site
Banovich_Kropski_2020   TGen               26582
                        VUMC               95312
Barbry_Leroy_2020       nan                74487
Jain_Misharin_2021      nan                45557
Krasnow_2020            nan                60982
Lafyatis_Rojas_2019     nan                24181
Meyer_2019              nan                35554
Misharin_2021           nan                64843
Misharin_Budinger_2018  nan                41220
Nawijn_2021             nan                70402
Seibold_2020            nan                33593
Teichmann_Meyer_2019    nan                12231
Name: count, dtype: int64

In [39]:
obs.value_counts(['study', 'Processing_site', 'assay', 'tissue_dissociation_protocol'], dropna=False, sort=False)

study                   Processing_site  assay      tissue_dissociation_protocol
Banovich_Kropski_2020   TGen             10x 5' v2  Dispase + collagenase              3946
                                         10x 5' v1  Dispase + collagenase             22636
                        VUMC             10x 5' v1  Dispase + collagenase             95312
Barbry_Leroy_2020       nan              10x 3' v2  Cold protease 1h                  74487
Jain_Misharin_2021      nan              10x 5' v2  Cold protease 1h                  33135
                                         10x 5' v1  Cold protease 1h                  12422
Krasnow_2020            nan              10x 3' v2  Collagenase + Elastase + DNAse    60982
Lafyatis_Rojas_2019     nan              10x 3' v2  Collagenase A + DNAse             21260
                                         10x 3' v1  Collagenase A + DNAse              2921
Meyer_2019              nan              10x 3' v2  Collagenase D + DNAse             35554
Misharin_2021           nan              10x 3' v3  Collagenase D + DNAse             64843
Misharin_Budinger_2018  nan              10x 3' v2  Collagenase D + DNAse             41220
Nawijn_2021             nan              10x 3' v2  Collagenase D + DNAse             70402
Seibold_2020            nan              10x 3' v2  Cold protease overnight           12127
                                         10x 3' v3  Cold protease overnight           21466
Teichmann_Meyer_2019    nan              10x 3' v2  Collagenase D + DNAse             12231
Name: count, dtype: int64